name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Use this to provide a version, instead of deriving it from the changelog.
        required: false
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      # The current realm studio release process keeps changes for the upcoming release
      # in a separate file (RELEASENOTES.md), and copies its content on top of the
      # changelog, before resetting it from a template.
      # The action used by other components keeps the release notes directly in
      # CHANGELOG.md, and just fills in the version. The format is slightly different
      # - but should be close enough that switching should be possible
      - name: Update Changelog
        id: update-changelog
        uses: realm/ci-actions/update-changelog@fa20eb972b9f018654fdb4e2c7afb52b0532f907
        with:
          changelog: ${{ github.workspace }}/CHANGELOG.md
          version: ${{ inputs.version }}
      - name: Update package.json
        uses: jacobtomlinson/gha-find-replace@0dfd0777cc234ef6947ec1f20873c632114c4167 #! 0.1.4
        with:
          find: '"version": "[^"]*"'
          replace: '"version": "${{ steps.update-changelog.outputs.new-version }}"'
          include: package.json
      - name: Create Release PR
        uses: peter-evans/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad #! 3.10.1
        with:
          branch: release/${{ steps.update-changelog.outputs.new-version }}
          title: Prepare for ${{ steps.update-changelog.outputs.new-version }}
          draft: false
          body: An automated PR for next release.
          commit-message: Prepare for ${{ steps.update-changelog.outputs.new-version }}
          token: ${{ secrets.REALM_CI_PAT }}
